// HTTP request router: serves the (embedded) single-file frontend and the
// JSON `/api/*` endpoints. Shared by both the windowed app (runs inside a
// worker) and the headless/dev server.
import * as db from "./db.js";
import * as recent from "./recent.js";
import { chooseSqliteFile } from "./dialog.js";

let cachedHtml = null;

/**
 * The built frontend is embedded as `./embedded.js` (generated by
 * `scripts/embed.js`). We import it lazily so that dev mode — where the page
 * is served by Vite with HMR, not by us — works even before a build exists.
 */
async function indexHtml() {
  if (cachedHtml !== null) return cachedHtml;
  try {
    const m = await import("./embedded.js");
    cachedHtml = m.INDEX_HTML;
  } catch {
    cachedHtml =
      `<!DOCTYPE html><html lang="zh"><head><meta charset="utf-8">` +
      `<title>SQLite GUI</title></head><body style="font-family:system-ui;padding:2rem;line-height:1.6">` +
      `<h2>前端尚未构建</h2><p>请先运行 <code>deno task build</code> 生成前端，再重新启动。</p></body></html>`;
  }
  return cachedHtml;
}

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}

function state() {
  return {
    path: db.currentPath(),
    tables: db.isOpen() ? db.listTables() : [],
    recent: recent.list(),
  };
}

async function handleApi(req, url, pathname) {
  switch (pathname) {
    case "/api/state":
    case "/api/tables":
      return json(state());

    case "/api/open": {
      if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);
      // An explicit `{ path }` opens that file directly (used by tests);
      // otherwise we pop the native file picker.
      let path = null;
      try {
        path = (await req.json())?.path ?? null;
      } catch {
        // no/blank body → show dialog
      }
      if (!path) path = await chooseSqliteFile();
      if (!path) return json({ canceled: true });
      const opened = db.openDatabase(path);
      recent.add(path);
      return json({ canceled: false, ...opened, recent: recent.list() });
    }

    case "/api/recent":
      return json({ recent: recent.list() });

    case "/api/recent/clear":
      if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);
      return json({ recent: recent.clear() });

    case "/api/rows": {
      const table = url.searchParams.get("table");
      if (!table) return json({ error: "缺少 table 参数" }, 400);
      return json(
        db.getRows(
          table,
          url.searchParams.get("page") ?? "1",
          url.searchParams.get("pageSize") ?? "50",
        ),
      );
    }

    default:
      return json({ error: "Not found" }, 404);
  }
}

export async function handleRequest(req) {
  const url = new URL(req.url);
  try {
    if (url.pathname.startsWith("/api/")) return await handleApi(req, url, url.pathname);
    // Single-page app: any other GET returns the frontend shell.
    if (req.method === "GET") {
      return new Response(await indexHtml(), {
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }
    return new Response("Not Found", { status: 404 });
  } catch (err) {
    return json({ error: err?.message ?? String(err) }, 400);
  }
}
