// Turns the Vite build output (`dist/index.html`, a single self-contained file
// thanks to vite-plugin-singlefile) into an importable JS module so that
// `deno compile` bundles the whole frontend straight into the executable.
//
// JSON.stringify produces a valid, fully-escaped JS string literal — safe for
// arbitrary HTML/JS/CSS content.
const distHtml = new URL("../dist/index.html", import.meta.url);
const target = new URL("../server/embedded.js", import.meta.url);

const html = await Deno.readTextFile(distHtml);
const module = `// AUTO-GENERATED by scripts/embed.js — do not edit by hand.\n` +
  `export const INDEX_HTML = ${JSON.stringify(html)};\n`;

await Deno.writeTextFile(target, module);
console.log(`Embedded dist/index.html (${html.length} bytes) → server/embedded.js`);
